<?php

namespace Modules\BrandOwner\Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;
use Modules\Branch\Models\Branch;
use Modules\BranchManagers\Models\BranchManager;
use Modules\BrandOwner\Models\BrandOwner;
use Modules\Custody\Models\CustodyTransaction;
use Modules\Expense\Models\Expense;
use Modules\Expense\Models\Supplier;

/**
 * Demo data for the Brand Owner Reports & Analytics screen.
 *
 * Seeds branches, managers, suppliers, expenses and custody transactions
 * spread across the current and previous month so the report endpoints
 * return meaningful summaries, trends and branch comparisons.
 *
 * It deliberately does NOT seed brand_owner_report_exports — export history
 * is meant to be generated by calling the export endpoints.
 *
 * No factories / faker are used, so it runs on production builds installed
 * with `composer install --no-dev`.
 *
 * Run it on its own:
 *   php artisan db:seed --class="Modules\BrandOwner\Database\Seeders\BrandOwnerReportsDemoSeeder"
 */
class BrandOwnerReportsDemoSeeder extends Seeder
{
    /** Branch-name suffix used as the "already seeded" marker. */
    private const MARKER = '(Demo)';

    public function run(): void
    {
        if (Branch::query()->where('name', 'like', '%'.self::MARKER)->exists()) {
            $this->command?->warn('Brand owner reports demo data already exists — skipping.');

            return;
        }

        $this->ensureBrandOwner();

        $now = Carbon::now();
        $thisMonth = $now->copy()->startOfMonth();
        $lastMonth = $now->copy()->subMonthNoOverflow()->startOfMonth();

        $suppliers = $this->createSuppliers(6);

        $branchDefs = [
            ['name' => 'Riyadh Central '.self::MARKER, 'location' => 'Riyadh'],
            ['name' => 'Jeddah Corniche '.self::MARKER, 'location' => 'Jeddah'],
            ['name' => 'Dammam Bay '.self::MARKER, 'location' => 'Dammam'],
        ];

        foreach ($branchDefs as $i => $def) {
            $branch = Branch::create([
                'name' => $def['name'],
                'location' => $def['location'],
            ]);

            $manager = BranchManager::create([
                'name' => $def['location'].' Manager',
                'email' => 'demo.manager.'.($i + 1).'@assab.test',
                'phone' => '+96650100000'.($i + 1),
                'password' => Hash::make('Password@123'),
                'branch_id' => $branch->id,
                'status' => 'active',
                'is_active' => true,
                'is_first_login' => false,
                'email_verified_at' => $now,
                'phone_verified_at' => $now,
            ]);

            // More expenses this month than last month, so trends move.
            $this->seedExpenses($manager->id, $suppliers, $thisMonth, 8 + $i * 2);
            $this->seedExpenses($manager->id, $suppliers, $lastMonth, 4 + $i);

            $this->seedCustody($manager->id, $branch->id, $thisMonth, 6);
            $this->seedCustody($manager->id, $branch->id, $lastMonth, 4);
        }

        $this->command?->info('Seeded reports demo data for '.count($branchDefs).' branches (current + previous month).');
    }

    private function ensureBrandOwner(): void
    {
        BrandOwner::updateOrCreate(
            ['email' => 'owner@assab.test'],
            [
                'name' => 'Brand Owner',
                'phone' => '+966500000001',
                'password' => Hash::make('Password@123'),
                'is_active' => true,
                'is_first_login' => false,
                'status' => 'active',
                'email_verified_at' => now(),
                'phone_verified_at' => now(),
            ]
        );
    }

    /** @return \Illuminate\Support\Collection<int, Supplier> */
    private function createSuppliers(int $count): \Illuminate\Support\Collection
    {
        $names = ['Al-Faisal Trading', 'Najd Foods', 'Gulf Supplies Co', 'Tamimi Markets', 'Rawabi Distribution', 'Sadara Wholesale'];
        $suppliers = collect();

        for ($n = 0; $n < $count; $n++) {
            $suppliers->push(Supplier::create([
                'name' => ($names[$n] ?? 'Demo Supplier '.($n + 1)).' '.self::MARKER,
                'email' => 'demo.supplier.'.($n + 1).'@assab.test',
                'phone' => '+96650200000'.($n + 1),
                'password' => Hash::make('Password@123'),
                'is_active' => true,
            ]));
        }

        return $suppliers;
    }

    /** Spread $count expenses across $monthStart, mixing type / status / VAT. */
    private function seedExpenses(string $managerId, $suppliers, Carbon $monthStart, int $count): void
    {
        $types = ['quick_cash', 'single_invoice', 'grouped_invoice'];
        $statuses = ['approved', 'pending', 'approved', 'rejected'];
        $methods = ['cash', 'supplier', 'custody'];

        for ($n = 0; $n < $count; $n++) {
            $type = $types[$n % count($types)];
            $hasVat = $n % 2 === 0;
            $net = random_int(200, 9000);
            $vat = $hasVat ? round($net * 0.15, 2) : 0;
            $when = $this->dayIn($monthStart, $n);

            Expense::create([
                'branch_manager_id' => $managerId,
                'expense_type' => $type,
                'status' => $statuses[$n % count($statuses)],
                'payment_method' => $methods[$n % count($methods)],
                'supplier_id' => $type === 'quick_cash' ? null : $suppliers->random()->id,
                'net_amount' => $net,
                'vat_amount' => $vat,
                'total_amount' => $net + $vat,
                'submitted_at' => $when,
                'created_at' => $when,
                'updated_at' => $when,
            ]);
        }
    }

    /** Spread $count custody transactions across $monthStart, alternating cash in/out. */
    private function seedCustody(string $managerId, string $branchId, Carbon $monthStart, int $count): void
    {
        $types = ['Cash Transfer', 'Cash Handover', 'Bank Transfer', 'Expenses Deduction'];

        for ($n = 0; $n < $count; $n++) {
            CustodyTransaction::create([
                'branch_manager_id' => $managerId,
                'branch_id' => $branchId,
                'type' => $types[$n % count($types)],
                'amount' => random_int(500, 12000),
                'is_cash_in' => $n % 2 === 0,
                'handover_method' => $n % 2 === 0 ? 'Cash Handover' : 'Bank Transfer',
                'transaction_date' => $this->dayIn($monthStart, $n),
            ]);
        }
    }

    /** A fixed-time date inside the given month, clamped to its length. */
    private function dayIn(Carbon $monthStart, int $offset): Carbon
    {
        $day = min($offset + 1, $monthStart->daysInMonth);

        return $monthStart->copy()->day($day)->setTime(10, 0);
    }
}
