<?php

namespace Modules\Notification\Repositories;

use Modules\Notification\Enums\NotificationChannel;

interface NotificationRepositoryInterface
{
    /**
     * Persist the in-app notification row under a caller-supplied id.
     *
     * The id is generated by the caller so every channel — push payloads,
     * delivery logs, deep links — can reference it without re-reading the table.
     *
     * @param  array<string, mixed>  $payload
     */
    public function record(object $notifiable, string $id, string $notificationClass, array $payload): void;

    public function logDelivery(
        string $notificationId,
        NotificationChannel $channel,
        string $status,
        ?string $errorMessage = null,
    ): void;
}
